// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog: dynamic(() => import("./QuemSomos")),
  post: dynamic(() => import("./Post")),
  text: dynamic(() => import("./Titulo")),
};
